### ISSUE TITLE
Config in `$XDG_CONFIG_HOME` not found.

### ISSUE THREAD

**Issue by citrusmunch** [KnorrFG/dotree#2]
I have a working config `$XDG_CONFIG_HOME/dotree.dt`, but `dt` seems to be looking elsewhere.

```ShellSession
❯ ls $XDG_CONFIG_HOME/dotree.dt && dt
/Users/cnmne/.config/dotree.dt
Expected config file at /Users/cnmne/Library/Application Support/dotree.dt, but couldn't find it. Please create one.
```

I also tried using `~/.config/dotree/dotree.dt` instead (which I know is not per the docs, but maybe more common elsewhere).

Of course I can successfully use `dt --conf-file ~/.config/dotree.dt` as a workaround, which I'll be aliasing in the meantime. Alternatively I could make a link to `Application Support`.

Also thanks for making this tool-- been looking for a `just` alternative; and a bonus: very [hydra](https://github.com/abo-abo/hydra)esque!

Also... ~~first! 🥇~~ second? 🥈

**Comment by KnorrFG** [comment]
Hey, thanks for the report. It seems you use MacOs? By default XDG was only respected on Linux. I changed the code so that it reads the env var on all platforms first, and tested it in wine. But before I make a new release, I'd like to know that it works on mac. Can you reinstall the latest master, and test it please?

**Comment by citrusmunch** [comment]
`dotree v0.5.2 (https://github.com/knorrfg/dotree?branch=main#6c183dee)` is working like a charm on macOS 12.7.
Thanks a bunch!
